language: python
python:
  - 3.7
branches:
  only:
  - main
before_install:
  - python --version
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install codecov
env:
  - CODECOV_TOKEN="533ccbb6-79b5-41ef-be83-1faa52f5cef6"
script: python -m unittest discover tests/
after_success:
  - codecov
