language: python
python:
  - 3.7
branches:
  only:
  - main
before_install:
  - python --version
  - pip install -U pip
  - pip install -r requirements.txt
  - pip install codecov
env:
  - CODECOV_TOKEN="b83163ee-4cd1-4810-927a-17249b3a6f97"
script: python -m unittest discover tests/
after_success:
  - codecov
